Flask/VCF_website/main/routes.py
from flask import render_template, request, Blueprint 
from VCF_website.query_results.routes import loading
from VCF_website.main.forms import SearchRs,SearchGene,SearchPos
# from VCF_website.results.

main = Blueprint("main",__name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/search", methods=['GET', 'POST'])
def search():
    # instantiating the forms seperately from the objects created in forms.py"""
    form1 = SearchPos()
    form2 = SearchRs()
    form3 = SearchGene()

    # Check if form 1 was submmited and validations passsed"""
    if form1.submit.data and form1.validate_on_submit():
        # Creating a Dictionary with form data if user searches via location
        # for ease of identifying data on other pages.        
        chromosome_position = {
            "chr": form1.select.data,
            "start_pos": form1.start_pos.data,
            "end_pos": form1.end_pos.data
        }       

        # Instead of loading the route we can directly call in the function so the datatype is maintained
        # else the dictionary turns into a string type.
        return loading(search=chromosome_position)
    
        # Check if form 2 was submmited and validations passsed. Values are of string class,
        # or a list of strings if multiple values seperated by commas are passed
    elif form2.rs_search.data and form2.validate_on_submit():
        return loading(search=form2.rs_val.data)

        
        # Check if form 3 was submmited and validations passsed. Values are of string class,
        # or a list of strings if multiple values seperated by commas are passed
    elif form3.gene_search.data and form3.validate_on_submit():
        return loading(search=form3.gene.data)
    return render_template('search.html', title='About', form1=form1, form2=form2, form3=form3)




# Redirects to documentation page
@main.route("/help", methods=['GET', 'POST'])
def help():
    return render_template('help.html', title='Contact')



# Create Custom Error Pages for improving user experience if non existing URL
# was searched or if unexpected issue arise

# Invalid URL
@main.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


# Internal Server Error
@main.errorhandler(500)
def page_not_found(e):
    return render_template("500.html"), 500

Flask/VCF_website/statistics/routes.py
from flask import render_template, url_for, flash, redirect, request, session, make_response,send_file, Blueprint
import VCF_website.statistics.genome_stats as gstat
from VCF_website.statistics.stats_utils import decompress
import ast
import json
from io import StringIO,BytesIO
import csv
from werkzeug.wrappers import Response

statistics = Blueprint("statistics",__name__)

@statistics.route("/stats")
@statistics.route("/stats/<pops>/<stats>/<bin>")
@statistics.route("/stats/<pops>/<stats>/<bin>/<step>")
def stats(pops= None, stats=None, bin=None, step = None):

    # If the data was store in sessions on a previous stats calc, load sessions so user can navigate around the site 
    # without having to redo the stats else, assumed to not have done any stats therefore expecting inputs for stats, population and bin size. 
    # If else also fails redirects results page to choose the parameters. 
    if not pops:
        try:
            html_first_col=json.loads(session['overall_location'])
            html_gene=json.loads(session['gene_names'])
            all_stats=json.loads(session['all_stats'])
            pop_stats = json.loads(session['pop_stats'])
            all_fstat =json.loads(session['all_fstat'])
            nuc_div_plot1=json.loads(session['nuc_div_plot1'])
            hap_div_plot1=json.loads(session['hap_div_plot1'])
            taj_d_plot1=json.loads(session['taj_d_plot1'])
            gbr_fst_plt= json.loads(session['gbr_fst_plt'])
            jpt_fst_plt=json.loads(session['jpt_fst_plt'])
            mxl_fst_plt=json.loads(session['mxl_fst_plt'])
            pjl_fst_plt=json.loads(session['pjl_fst_plt'])
            yri_fst_plt=json.loads(session['yri_fst_plt'])
            
            return render_template('stats.html',
            html_first_col=html_first_col,
            html_gene=html_gene,
            all_stats=all_stats,
            pop_stats = pop_stats,
            all_fstat = all_fstat,
            nuc_div_plot1=nuc_div_plot1,
            hap_div_plot1=hap_div_plot1,
            taj_d_plot1=taj_d_plot1,
            gbr_fst_plt= gbr_fst_plt,
            jpt_fst_plt=jpt_fst_plt,
            mxl_fst_plt=mxl_fst_plt,
            pjl_fst_plt=pjl_fst_plt,
            yri_fst_plt=yri_fst_plt
            )
        except:
            pass


    else:

        # Expecting User to pass in valid values via GET request. Formatting issues can cause it to raise an error 
        # and redirect them back to results page to properly pass them in. The user input format has to be specific 
        # so they cant manually type them in the URL.
        try:
            # Checking if the user selected more than one population which is passed a string list i.e ("['pop1','pop2',]")
            if pops.startswith('[') :
                # converts a string list into an acutal list type data
                sel_pops = ast.literal_eval(pops)       
            else:
                """ Creating a list with one element if user selected just one population"""
                sel_pops = [pops]  
            
            # Similarly checking if the user selected more than one stat which is passed a string list i.e ("['stat1','stat2',]")
            if stats.startswith('['):
                stats_sel = ast.literal_eval(stats) 
            else:
                stats_sel = [stats]

            # Get the bin size
            bin_size = int(bin)

            # Get the stepsize if user provided them
            if step:
                step_size = int(step)
            else:
                step_size =None
        except Exception:
            flash ('Please select the Stats and populations from this page', 'info')
            return redirect(url_for('query_results.results'))


        # Load the query session to perform calculations    
        results = json.loads(session['results'])
        gen_pos = [int(i['pos']) for i in results]


        # Summary Stats for each population
        #  GBR
        if 'GBR' in sel_pops:
            # Load the data via sessions
            gbr = json.loads(session['gbr'])
            gbr_gt_data, gbr_freq = decompress(gbr)

            # Get homozygositym nucleotide diversity, haplotype diversity, and Tajimas D        
            gbr_homo, gbr_nuc_div, gbr_hap_div, gbr_taj_d = gstat.get_main_stats(pop=gbr_gt_data, freq_data =gbr_freq, pos=gen_pos, stats=stats_sel)
            gbr_stats = ['GBR',gbr_homo, gbr_nuc_div, gbr_hap_div, gbr_taj_d]

            # Windowed Satats
            # PI
            gbr_win_pi= gstat.win_nuc_div(positions=gen_pos, pop=gbr_gt_data, bin_size=bin_size, step_size=step_size)

            # Tajimas D
            gbr_win_taj_D= gstat.win_tajima_d(positions=gen_pos,pop=gbr_gt_data,bin_size=bin_size,step_size=step_size)

            #  Haplotype
            gbr_win_hap = gstat.win_haplotype_div(positions=gen_pos,pop=gbr_gt_data,bin_size=bin_size,step_size=step_size)
        else:
            gbr = None


        # JPT
        # Load the data via sessions
        if 'JPT' in sel_pops:
            jpt = json.loads(session['jpt'])
            jpt_gt_data, jpt_freq = decompress(jpt)

            # Get homozygositym nucleotide diversity, haplotype diversity, and Tajimas D
            jpt_homo, jpt_nuc_div, jpt_hap_div, jpt_taj_d = gstat.get_main_stats(pop=jpt_gt_data, freq_data=jpt_freq, pos=gen_pos, stats=stats_sel)
            jpt_stats = ['JPT',jpt_homo, jpt_nuc_div, jpt_hap_div, jpt_taj_d]

            # Windowed Satats

            # PI
            jpt_win_pi=  gstat.win_nuc_div(positions=gen_pos,pop=jpt_gt_data,bin_size=bin_size,step_size=step_size)

            # Tajimas D
            jpt_win_taj_D= gstat.win_tajima_d(positions=gen_pos,pop=jpt_gt_data,bin_size=bin_size,step_size=step_size)

            # Haplotype
            jpt_win_hap = gstat.win_haplotype_div(positions=gen_pos,pop=jpt_gt_data,bin_size=bin_size,step_size=step_size)
        else:
            jpt = None
        
        
        # MXL
        # Load the data via sessions
        if 'MXL' in sel_pops:
            mxl = json.loads(session['mxl'])
            mxl_gt_data, mxl_freq = decompress(mxl)
            # Get homozygositym nucleotide diversity, haplotype diversity, and Tajimas D
            mxl_homo, mxl_nuc_div, mxl_hap_div, mxl_taj_d = gstat.get_main_stats(pop=mxl_gt_data,freq_data =mxl_freq,pos=gen_pos,stats=stats_sel)
            mxl_stats = ['MXL',mxl_homo, mxl_nuc_div, mxl_hap_div, mxl_taj_d]

            # Windowed Satats
            # PI
            mxl_win_pi=  gstat.win_nuc_div(positions=gen_pos,pop=mxl_gt_data,bin_size=bin_size,step_size=step_size)

            # Tajimas D
            mxl_win_taj_D= gstat.win_tajima_d(positions=gen_pos,pop=mxl_gt_data,bin_size=bin_size,step_size=step_size)

            # Haplotype
            mxl_win_hap = gstat.win_haplotype_div(positions=gen_pos,pop=mxl_gt_data,bin_size=bin_size,step_size=step_size)
        else:
            mxl = None


        # PJL
        # Load the data via sessions
        if 'PJL' in sel_pops:
            pjl = json.loads(session['pjl'])
            pjl_gt_data, pjl_freq = decompress(pjl)
            # Get homozygositym nucleotide diversity, haplotype diversity, and Tajimas D
            pjl_homo, pjl_nuc_div, pjl_hap_div, pjl_taj_d = gstat.get_main_stats(pop=pjl_gt_data,freq_data =pjl_freq,pos=gen_pos,stats=stats_sel)
            pjl_stats = ['PJL',pjl_homo, pjl_nuc_div, pjl_hap_div, pjl_taj_d]

            # Windowed Satats
            # PI
            pjl_win_pi=  gstat.win_nuc_div(positions=gen_pos,pop=pjl_gt_data,bin_size=bin_size,step_size=step_size)

            # Tajimas D
            pjl_win_taj_D= gstat.win_tajima_d(positions=gen_pos,pop=pjl_gt_data,bin_size=bin_size,step_size=step_size)

            # Haplotype
            pjl_win_hap = gstat.win_haplotype_div(positions=gen_pos,pop=pjl_gt_data,bin_size=bin_size,step_size=step_size)
        else:
            pjl = None


        # YRI
        # Load the data via sessions
        if 'YRI' in sel_pops:
            yri = json.loads(session['yri'])
            yri_gt_data, yri_freq = decompress(yri)
            # Get homozygosity nucleotide diversity, haplotype diversity, and Tajimas D
            yri_homo,yri_nuc_div,yri_hap_div,yri_taj_d = gstat.get_main_stats(pop=yri_gt_data,freq_data =yri_freq,pos=gen_pos,stats=stats_sel)
            yri_stats = ['YRI',yri_homo,yri_nuc_div,yri_hap_div,yri_taj_d]

            # Windowed Stats
            # PI
            yri_win_pi=  gstat.win_nuc_div(positions=gen_pos,pop=yri_gt_data,bin_size=bin_size,step_size=step_size)

            # Tajimas D
            yri_win_taj_D= gstat.win_tajima_d(positions=gen_pos,pop=yri_gt_data,bin_size=bin_size,step_size=step_size)

            # Haplotype
            yri_win_hap = gstat.win_haplotype_div(positions=gen_pos,pop=yri_gt_data,bin_size=bin_size,step_size=step_size)
        else:
            yri = None



        # For calculating fstats, creating a dictionary with key as the population code  and value as the array
        gt_dict = {}
        gt_freq = {}


        # This is for creating a dictionary of all the summary statistics calculated from above (no windows included)
        # so its easier to use jija2 to dynamically create the tables and their stts for individual populations
        pop_stats = {}


        #For creating plots
        plot_pi ={}
        plot_taj_d = {}
        plot_hap = {}

        
        # If the user seleceted the population assigning the genotype and frequency data to a diction with their key
        if gbr:
            # For fst stats
            gt_dict['GBR'] = gbr_gt_data

            # Purely for calculating overall stats
            gt_freq['GBR'] = gbr_freq

            # For displauing on the table as individual stats
            pop_stats['GBR'] = gbr_stats

            # For all plots
            plot_pi['GBR'] = gbr_win_pi
            plot_taj_d['GBR']=gbr_win_taj_D
            plot_hap['GBR'] = gbr_win_hap

        if jpt:

Flask/VCF_website/templates/about.html
{% extends "layout.html" %} 
{% block content %}
  <!-- Oursite" -->
  <div class="w3-container w3-light-grey" style="padding: 50px 16px">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <img class="w3-image w3-round-large center" style="float: left" src="..\static\profile_pics\POPgen-logos_black.png" alt="Buildings" width="50%" />
      </div>
      <div class="col-sm-12 col-md-6">
        <h3 style="margin-top: 10%">POPgen</h3>
        <p>
          POPgen explores the annotation and description of single nucleotide
          polymorphisms (SNPs) within five human populations. SNPs are the key
          controllers of genetic diversity. POPgen provides a user-friendly
          application that takes inputs of genomics coordinates, SNP name or gene
          name and retrieves SNP information such as rs id, genomic position,
          genotype frequency and allele frequency. We wrangled the sequencing data
          specifically to the human chromosome 22 from five different populations
          around the world.
        </p>
        <br />
        <p>
          <a target="_blank" href="{{ url_for('main.help') }}" class="w3-button w3-black w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Documentation</a>
        </p>
      </div>
    </div>
  </div>
  <!-- IGSR" -->
  <div class="w3-container w3-white" style="padding: 50px 10px">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h3>IGSR</h3>
        <p>
          The International Genome Sample Resource collects data from multiple
          human populations through Variant Call Format (VCF) files, containing
          genotype/haplotype information for sequenced samples at each called SNP.
          IGSR provided our team with the usability and accessibility of data from
          the 1000 Genomes Project.
        </p>
        <br />
        <p>
          <a target="_blank" href="https://www.internationalgenome.org/home" class="w3-button w3-black w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">IGSR Website</a>
        </p>
      </div>
      <div class="col-sm-12 col-md-6">
        <img class="w3-image w3-round-large center" src="..\static\profile_pics\IGSR.jpg" alt="Buildings" width="400" />
      </div>
    </div>
  </div>

  <!-- Population Genomics" -->
  <div class="w3-container w3-light-grey" style="padding: 16%">
    <div class="w3-row-padding w3-center">
      <div class="w3-col m12">
        <h3 style="margin-top: -5%; margin-bottom: 5%">POPULATION GENOMICS</h3>
        <br />
        <p>
          Population genomics is the study of genetic variation within and between
          populations and the evolutionary factors that explain this variation.
          Through the analysis of genetic variation, inferences from population
          genomic data can be applied to conservation genetics, evolutionary
          biology and precision medicine, etc. The advent of next-generation
          sequencing (NGS) technologies has provided a surge of genomic data from
          several populations, helping to improve our understanding of the
          evolutionary history in and between populations.
        </p>
        <p>
          <a target="_blank" href="https://en.wikipedia.org/wiki/Population_genomics"class="w3-button w3-black w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Wiki Page</a>
        </p>
      </div>
    </div>
  </div>
{% endblock content %}

Flask/VCF_website/templates/download.html
{% extends "layout.html" %}
{% block content %}
    <h1>DOWNLOAD</h1>
{% endblock content %}

Flask/VCF_website/templates/download_stats.html
{% extends "layout.html" %}
{% block content %}
<h1>DOWNLOAD STATS</h1>
{% endblock content %}

Flask/VCF_website/templates/home.html
{% extends "layout.html" %} 
{% block content %}
    <header class="bgimg-1 w3-display-container w3-grayscale-min" id="home">
      <div class="w3-display-left w3-text-Black" style="padding:48px">
        <span class="w3-jumbo w3-hide-small">Population Genomics</span><br>
        <span class="w3-xxlarge w3-hide-large w3-hide-medium">Population Genomics</span><br>
        <span class="w3-large">Search for variation across chromosomes and perform basic analysis</span>
        <p><a href="{{ url_for('main.search') }}"class="w3-button w3-black w3-margin-top w3-opacity w3-hover-opacity-off">Search For SNPs</a></p>
      </div>
    </header>

    <div class="container" style="padding:128px 16px" id="team">
      <h3 class="w3-center">THE TEAM</h3>
      <p class="w3-center w3-large">The ones who Created this Web App</p>
      <div class="row justify-content-md-center">

        
        <div class="col-sm-12 col-md-6 col-lg-2 d-flex">
          <div class="card">
            <img class="center" src="https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/user_female2-512.png" alt="Github Pic" style="width:80%">
            <div class="card-body">
              <h3>Alexandra</h3>
              <p class="w3-opacity">Data Collection and Documentation </p>
            </div>
            <div class="card-footer">
              <button class="w3-button w3-light-grey w3-block">
                <a target="_blank" href="https://github.com/alexxandra00"><i class="fa fa-github"></i></a>
              </button>
            </div>
          </div>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-2 d-flex">
          <div class="card">
            <img class="card-img-top center" src="https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/user_male2-512.png" alt="Github Pic" style="width: 80%" />
            <div class="card-body">
              <h3>Harry</h3>
              <p class="w3-opacity">Front End Dev</p>
            </div>
            <div class="card-footer">
              <button class="w3-button w3-light-grey w3-block">
                <a target="_blank" href="https://github.com/HarryArthurMarchant"><i class="fa fa-github"></i></a>
              </button>
            </div>
          </div>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-2 d-flex">
          <div class="card">
            <img class="card-img-top center" src="https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/user_male2-512.png" alt="Github Pic" style="width: 80%" />
            <div class="card-body">
              <h3>Waleed</h3>
              <p class="w3-opacity">Database Engineer</p>
            </div>
            <div class="card-footer">
              <button class="w3-button w3-light-grey w3-block">
                <a target="_blank" href="https://github.com/AbuKamaal"><i class="fa fa-github"></i></a>
              </button>
            </div>
          </div>
        </div>


        <div class="col-sm-12 col-md-6 col-lg-2 d-flex">
          <div class="card">
            <img class="card-img-top center" src="https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/user_male2-512.png" alt="Github Pic" style="width: 80%" />
            <div class="card-body">
             <h3>Mani</h3>
              <p class="w3-opacity">Backend Dev</p>
            </div>
            <div class="card-footer">
              <button class="w3-button w3-light-grey w3-block">
                <a target="_blank" href="https://github.com/Mani-varma1"><i class="fa fa-github"></i></a>
              </button>
            </div>
          </div>
        </div>


        <div class="col-sm-12 col-md-6 col-lg-2 d-flex">
          <div class="card">
            <img class="card-img-top center" src="https://cdn2.iconfinder.com/data/icons/ios-7-icons/50/user_female2-512.png" alt="Github Pic" style="width: 80%" />
            <div class="card-body">
              <h3>Laavanya</h3>
              <p class="w3-opacity">Statistician and data Visualisation</p>
            </div>
            <div class="card-footer">
              <button class="w3-button w3-light-grey w3-block">
                <a target="_blank" href="https://github.com/Laavanya741"><i class="fa fa-github"></i></a>
              </button>
            </div>
          </div>
        </div>

      </div>
    </div> 
    <!-- Footer -->
    <footer class="w3-center w3-black w3-padding-64">
      <p>Powered by: <span class="w3-hover-text-green">Caffine Overdose and Slepless Nights</span></p>
    </footer>
{% endblock content %}

Flask/VCF_website/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


  {% if title %}
  <title>Population Genomics - {{ title }}</title>
  {% else %}
  <title>Population Genomics</title>
  {% endif %}


</head>

<body>
<!-- Navbar -->
<div class="w3-top" style="border-bottom: 50px;">
  <div class="w3-bar w3-black w3-card" id="myNavbar">
    <a href="/" class="w3-bar-item w3-button w3-wide">POPgen</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      {% if not session['results'] %}
      <a href="{{ url_for('main.home') }}" class="w3-bar-item w3-button"><i class="fa fa-home"></i>HOME</a>
      <a href="{{ url_for('main.about') }}" class="w3-bar-item w3-button"><i class="fa fa-book"></i>ABOUT</a>
      <a href="{{ url_for('main.search') }}" class="w3-bar-item w3-button"><i class="fa fa-binoculars"></i> SEARCH</a>
      <a target="_blank" href="{{ url_for('main.help') }}" class="w3-bar-item w3-button"><i class="fa fa-book"></i> HELP</a>
      {% endif %}
      {% if session['results'] %}
        <a href="{{ url_for('main.home') }}" class="w3-bar-item w3-button"><i class="fa fa-home"></i>HOME</a>
        <a href="{{ url_for('main.about') }}" class="w3-bar-item w3-button"><i class="fa fa-book"></i>ABOUT</a>
        <a href="{{ url_for('main.search') }}" class="w3-bar-item w3-button"><i class="fa fa-binoculars"></i> SEARCH</a>
        <a href="{{ url_for('main.help') }}" class="w3-bar-item w3-button"><i class="fa fa-book"></i> HELP</a>
        <a href="{{ url_for('query_results.results') }}" class="w3-bar-item w3-button"> RESULTS</a>
        <a target="_blank" href="{{ url_for('statistics.stats', pops= None, stats=None, bin=None, step=None) }}" class="w3-bar-item w3-button"> STATS</a>
      {% endif %}
    </div>
  </div>
</div>
    <!-- for Home and Bout page using W3Schools -->
    {% block content %}{% endblock %}
    
    <!-- For search and results page using Boot strap -->
    <main role="main" class="container mt-5">
      <div class="row">
        <div class="col-md-8 mt-5">
          {% with messages = get_flashed_messages(with_categories=True) %}
            {%if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          
          {% block search %}{% endblock %}
        </div>
      </div>
    </main>



  <script type="text/javascript">
    function loading() {
      $("#loading1").show();
      $("#content-dsip1").hide();
      $("#loading2").show();
      $("#content-dsip2").hide();
      $("#loading3").show();
      $("#content-dsip3").hide();
    }
  </script>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>